// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_primitive = require("bs-platform/lib/js/caml_primitive.js");

function compare(a, b) {
  return Caml_primitive.caml_int_compare(a[/* id */0], b[/* id */0]);
}

exports.compare = compare;
/* No side effect */
