// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Slider");

function valueFromEvent(evt) {
  return evt.target.value;
}

function make(min, max, step, $$default, $staropt$star, onChange, _) {
  var title = $staropt$star !== undefined ? $staropt$star : "";
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, title, React.createElement("input", {
                              max: String(max),
                              min: min,
                              step: step,
                              type: "range",
                              value: self[/* state */1][/* value */0].toString(),
                              onChange: (function (evt) {
                                  var v = evt.target.value;
                                  Curry._1(onChange, v);
                                  return Curry._1(self[/* send */3], /* ValueChanged */[v]);
                                })
                            }), self[/* state */1][/* value */0].toString());
            }),
          /* initialState */(function () {
              return /* record */[/* value */$$default];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* value */action[0]]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.valueFromEvent = valueFromEvent;
exports.make = make;
/* component Not a pure module */
